# Generated by Django 4.2.1 on 2023-06-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='image',
            new_name='P_image',
        ),
    ]
