# Generated by Django 4.2.1 on 2023-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_image_delete_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
        migrations.DeleteModel(
            name='Profile_image',
        ),
    ]
