# Generated by Django 4.2.1 on 2023-06-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_image_delete_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
