# Generated by Django 4.2.1 on 2023-05-27 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Description', models.TextField(default='', max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Brand', models.CharField(default='', max_length=200)),
                ('Category', models.CharField(choices=[('Electronics', 'Electronics'), ('Laptop', 'Laptop'), ('Arts', 'Arts'), ('Food', 'Food'), ('Home', 'Home'), ('Kitchen', 'Kitchen')], max_length=30)),
                ('Rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('Stock', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
