# Generated by Django 4.2.1 on 2023-05-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User',
            new_name='user',
        ),
    ]
