# Generated by Django 4.2.1 on 2023-05-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_user_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='User',
        ),
    ]
