# Generated by Django 4.2.1 on 2023-05-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_city_alter_order_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oreder',
            new_name='order',
        ),
    ]
